# From https://github.com/MicrosoftDocs/pipelines-anaconda/blob/master/azure-pipelines.yml

jobs:
- job:
  displayName: vs2017-win2016
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      # Python27:
      #   python.version: '2.7'
      Python36:
        python.version: '3.6'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda env create environment.yml
    displayName: Create Anaconda environment

  - script: |
      call activate pm21
      python -c "import sys; print(sys.version)"
      python -c "import numpy"
      python -c "import matplotlib"
      python -c "import pandas"
      python -c "import scipy"
      python -c "import pymc3"
      python -c "import seaborn"
      python -c "import imageio"
      python -c "import sklearn"
      python -c "import skimage"
      python -c "import adskalman"
      python -c "import dabest"
      python -c "import showast"
    displayName: test Python version and imports
